"""Stable public contracts for third-party Strata plugins."""

from strata_cms.plugin_api.blocks import (
    MAX_BLOCK_NESTING_DEPTH,
    BlockCollection,
    BlockDefinition,
    BlockDeliverySerializer,
    BlockFieldDefinition,
    BlockId,
    BlockListConstraint,
    BlockNode,
    BlockSchema,
    BlockSlotDefinition,
    BlockTypeKey,
    EncodedBlockData,
)
from strata_cms.plugin_api.definitions import (
    ContentCapability,
    ContentTypeDefinition,
    EncodedContent,
    PluginDefinition,
    PluginRequirement,
)
from strata_cms.plugin_api.editor import (
    BlockCollectionEditorField,
    BlockEditorDefinition,
    BlockSlotEditorDefinition,
    ContentEditorDefinition,
    EditorChoice,
    EditorInputKind,
    ScalarEditorField,
)
from strata_cms.plugin_api.errors import (
    BlockTypeNotFoundError,
    BlockValidationError,
    ContentTypeNotFoundError,
    ContentValidationError,
    DuplicateBlockTypeError,
    InvalidBlockEnvelopeError,
    InvalidSchemaMigrationError,
    PluginAPIError,
    RegistryConfigurationError,
    SchemaDecodeError,
    UndeclaredPluginDependencyError,
    UnknownBlockReferenceError,
    UnsupportedSchemaVersionError,
)
from strata_cms.plugin_api.keys import PluginKey
from strata_cms.plugin_api.migrations import SchemaMigration, SchemaMigrationSet
from strata_cms.plugin_api.registry import (
    STRATA_PLUGIN_API_VERSION,
    PluginRegistrar,
    StrataRegistry,
    StrataRegistryBuilder,
)
from strata_cms.plugin_api.schema import (
    ContentDeliverySerializer,
    ContentSchema,
    ValidationIssue,
)

__all__ = [
    "MAX_BLOCK_NESTING_DEPTH",
    "STRATA_PLUGIN_API_VERSION",
    "BlockCollection",
    "BlockCollectionEditorField",
    "BlockDefinition",
    "BlockDeliverySerializer",
    "BlockEditorDefinition",
    "BlockFieldDefinition",
    "BlockId",
    "BlockListConstraint",
    "BlockNode",
    "BlockSchema",
    "BlockSlotDefinition",
    "BlockSlotEditorDefinition",
    "BlockTypeKey",
    "BlockTypeNotFoundError",
    "BlockValidationError",
    "ContentCapability",
    "ContentDeliverySerializer",
    "ContentEditorDefinition",
    "ContentSchema",
    "ContentTypeDefinition",
    "ContentTypeNotFoundError",
    "ContentValidationError",
    "DuplicateBlockTypeError",
    "EditorChoice",
    "EditorInputKind",
    "EncodedBlockData",
    "EncodedContent",
    "InvalidBlockEnvelopeError",
    "InvalidSchemaMigrationError",
    "PluginAPIError",
    "PluginDefinition",
    "PluginKey",
    "PluginRegistrar",
    "PluginRequirement",
    "RegistryConfigurationError",
    "ScalarEditorField",
    "SchemaDecodeError",
    "SchemaMigration",
    "SchemaMigrationSet",
    "StrataRegistry",
    "StrataRegistryBuilder",
    "UndeclaredPluginDependencyError",
    "UnknownBlockReferenceError",
    "UnsupportedSchemaVersionError",
    "ValidationIssue",
]
